### ISSUE TITLE
Check and confirm behavior on various URLS 

### ISSUE THREAD

**Issue by mitra42** [abhidas17695/dweb-ext#10]
Please test each of these, and create issues if any don't work as expected (note the problem could be in the bundled code of course) . 

* dweb.archive.org -> should end up booting into the archive site
* dweb.foo.com -> Should end up failing and trying the real dweb.foo.com (it probably doesn't yet)
* www.iskme.org -> should never be intercepted and should go direct to www.iskme.org
* dweb.me -> Should not be intercepted - it could end up in a loop - but need to figure out how

**Comment by abhidas17695** [comment]
Code addresses this issue although present version of extension assumes all URLs to be dweb.archive.org

**Comment by mitra42** [comment]
Release in #22 has a problem with the dweb.foo.com example

**Comment by mitra42** [comment]
Add to the list of test URLS

* https://dweb.archive.org/details/commute -> should go to https://dweb.me/archive/archive.html?item=commute (which is what domain resolution should be sending back)
* https://dweb.archive.org?verbose=true -> should go to the site with verbose=true (or any other parameters) set.

**Comment by mitra42** [comment]
These are all working. Leaving this open just for testing purposes in case we make changes.

**Comment by mitra42** [comment]
WE can close this as we aren't editing that code any more.
