### ISSUE TITLE
Why is the bootloader.html page showing up

### ISSUE THREAD

**Issue by mitra42** [abhidas17695/dweb-ext#15]
Before the final page loads, I'm seeing `bootloader.html` loading, or rather I'm seeing HTML that looks like it comes from bootloader.html.   I can't find that html in the extension, which suggests its trying to load dweb.archive.org from the server (which would deliver that page).  Or is there somewhere else that bootloader.html is coming form. 

What I don't understand is how it gets there, isn't the dweb-ext supposed to be intercepting the load to dweb.archive.org  ?

**Comment by mitra42** [comment]
Wondering if this is related to #17 since "bootloader.html" would be what the browser is trying to load when onCompleted is triggered (I think, but could be wrong)

**Comment by abhidas17695** [comment]
Yes since the extension is kicking in after the page loads , you will see bootloader.html before being redirected.

**Comment by mitra42** [comment]
See comment just made on #16

**Comment by abhidas17695** [comment]
See #21

**Comment by mitra42** [comment]
Looks good
