### ISSUE TITLE
Dealing with need to reload extension

### ISSUE THREAD

**Issue by mitra42** [abhidas17695/dweb-ext#17]
Moving conversation here about why we need to reload extension ... 
@abhidas17695 says it is because of the background scrips. 
I asked .... 

OK - so lets think about that deeper … background scripts being persistent is good for dweb. The question I think is how to avoid restarting them, and instead to call them.  Can you check for example if the global “DwebTransports” is loaded ?

**Comment by abhidas17695** [comment]
Yes DwebTransports is accessible in bootloader.js

**Comment by mitra42** [comment]
its persistant now, but would be good to be able to access DwebTransports etc without reloading the libraries in the actual page.

**Comment by mitra42** [comment]
Note - that might not be possible or even improve things if it can only tell this AFTER loading the bundle.

**Comment by mitra42** [comment]
This would be a good small project, to see if there is a way in for example dweb-archive/archive.html to only load dweb-transports bundle again if its not usable on the dweb-ext.  It might not be possible (without making other things worse), but its worth some research.

**Comment by mitra42** [comment]
Closing since we aren't reloading and the issue in the last comments is in #29
