### ISSUE TITLE
Directions to build all the code -- we can't see what you are doing to check assumptions etc

### ISSUE THREAD

**Issue by mitra42** [abhidas17695/dweb-ext#18]
We need directions to make bundle.js, ideally inside the dweb-ext repo, but can be a separate repo if you need that repo to just be the extension. Also if you are modifying dweb-object then the changes being made need to be in a repo, and properly checked in so we can see what you are doing.

**Comment by abhidas17695** [comment]
Latest commit address this issue. All files and instructions to build the bundles included.

**Comment by mitra42** [comment]
Are there any changes to dweb-transports, or is this just a copy of the dweb-transports repo ?

**Comment by abhidas17695** [comment]
dweb-transports is a copy of the original forked from your account. Only change is to dweb-objects in Domain.js at line 178.

**Comment by mitra42** [comment]
Can you update the instructions to include the full flow ... it seems from your comment on #3 
`Using webpack for now. Build instructions for the current version are in README.md. Source repos at https://github.com/abhidas17695/dweb-transports/tree/ext and https://github.com/abhidas17695/dweb-objects/tree/ext will be updates as and when needed` that the process for a change involves copying the code somehow (how are you doing this) from internetarchive/dweb-objects -> abhidas17695/dweb-objects -> dweb-ext/objects before this build ?

**Comment by abhidas17695** [comment]
Yes I will.
