### ISSUE TITLE
Urls not being passed through correctly.

### ISSUE THREAD

**Issue by mitra42** [abhidas17695/dweb-ext#19]
URLs aren’t being passed through correctly, for example
dweb.archive.org/details/commute  -> https://dweb.me/arc/archive.org/details? 
That might just be part of your testing (that loads the url “https://dweb.archive.org”
(See https://github.com/abhidas17695/dweb-ext/issues/18  - I can’t check whether this is the case since I can’t see your source code and/or changes to dweb-objects etc)

**Comment by abhidas17695** [comment]
The extension assumes all URLs are https://dweb.archive.org. This is done such that it is possible to test whether the extension is actually working or not since it is not possible to convey much useful information through logs as too many errors are logged because of this hack.

**Comment by abhidas17695** [comment]
Latest commit solves this

**Comment by mitra42** [comment]
Fixed by #26
