### ISSUE TITLE
Latest commit : passing openChrome as argument and using chrome.tabs.open() is true

### ISSUE THREAD

**Issue by abhidas17695** [abhidas17695/dweb-ext#26]
No change in behavior. `Signature not verified` error remains. Not more than 1 URL can be intercepted

**Comment by mitra42** [comment]
I'm trying to find where the source code with the changes to Domain.js is ?

**Comment by mitra42** [comment]
So that I can a) see what has been changed and b) put it into dweb-objects library

**Comment by mitra42** [comment]
See notes in Slack - changed to openChromeTab and put into {} args of each function reqd.
