### ISSUE TITLE
Occasional loads of page without specifiying it

### ISSUE THREAD

**Issue by mitra42** [abhidas17695/dweb-ext#28]
I'm seeing it load the dweb.me/archive page at surprising times, I've noticed whlle debugging that the extension appears to be working when triggered by Chrome's auto background loading e.g. when I type "d" at the start of a URL. 

Its probably good to start the resolution process, but not to boot - is there any way to tell whether a call to the listener is the pre-load or a real URL load.

**Comment by abhidas17695** [comment]
Would this problem occur only when you open a new tab ? I noticed this problem too but the extension would start when I opened a new tab and redirected it to the previous invocation's `url.href` . That is why I added `!details.url.startsWith('chrome')` at line 54 of bootloader.js

**Comment by mitra42** [comment]
If I open a new tab, and type "d" then it sometimes triggers the extension, it seems to be doing a preload of the page "https://dweb.archive.org" which is hte first thing offered in the dropdown.  The extension runs all the way through and then fails to open the page because the tab id is wrong. (we don't want it opening the page at that point)

**Comment by abhidas17695** [comment]
I am looking into it

**Comment by mitra42** [comment]
Abhishek asked in Slack .... whether the setting was "Use a prediction service to load pages more quickly" and whether I was still seeing it.

**Comment by mitra42** [comment]
I'm still seeing it.  I have this setting and the one  immediately before it - "Use a prediction service ... URLS typed in the address bar".  
Sometimes I have to get halfway through typing the address... To see it:
* Open the Extension background page, 
* arrange windows so you can see both this background page, and the main window. 
* In the URL bar start SLOWLY typing `dweb.archive.org` one character at a time, watching the extension console.  
* On my current test when I got to `dweb.arc` it triggered the prediction service which ran the extension

**Comment by abhidas17695** [comment]
Yes I finally reproduced this bug. The extension wasn't redirecting my tab but the status updates were logged to the console. I had to wait for 5-10 seconds after each keystroke.

**Comment by mitra42** [comment]
Great - is there a way to tell from the listener event if its a predicted load, or a real one?

**Comment by abhidas17695** [comment]
Let me research this for a bit.

**Comment by abhidas17695** [comment]
@mitra42 please see #33

**Comment by mitra42** [comment]
Looks like that fixed it - closing this (will reopen if I see it again)
