### ISSUE TITLE
Starting transports

### ISSUE THREAD

**Issue by mitra42** [abhidas17695/dweb-ext#30]
I'm currently starting transports in bootloader.js which I believe means when the extension is loaded, this starts IPFS and WebTorrent etc.  That could slow things down even when not in the dweb, so I think we need.
a) a flag in bootloader.js - "const startTransportsAtLoad = false" 
b) If that flag is set then start as now (last line of bootloader.js) 
c) If not set, then start the first time we intercept a matching URL.

**Comment by abhidas17695** [comment]
Do we want `DwebTransports.p_connect({ });` just once ? Or do we want `DwebTransports.p_connect({ });` to run as many times as a new URL is intercepted ?

**Comment by mitra42** [comment]
Just once - your original version ran it multiple times; the current version runs once on loading; I'd like it to run once the FIRST time a URL is intercepted, but to be able to control that behavior via the flag I mentioned 2 comments above.

**Comment by abhidas17695** [comment]
I get it

**Comment by mitra42** [comment]
I notice this is worked on in current release. (please comment in Git when you work on things with a related issue). 
I notice three things. 
a) Equality tests should almost always be === not == (read up on the difference, its subtle) 
b) There are two tests ... it should work as currently written but I think:

  * the one in the Listener would be clearer as `if (!transportsLoaded) ` because you always want a started transport in the listener. 
  * the one at the bottom is `if (startTransportsAtLoad)`, as you only need to check if start is desired in the load-time test, it can't have been loaded already. 
 * the p_connect({}) is async, so I think it should be.   p_connect({}).then(()=>main(url, details,tabId)) since you want to run main AFTER p_connect completes. 

Combining these two things, I think this makes the desired code in the Listener. : 

```
if (!transportsLoaded) { 
  p_connect({}).then(()->main(url, details, tabId));
} else {
  main(url,details, tabId);
}
```
I have not tested this yet.

**Comment by mitra42** [comment]
This would explain why I see "cat find any transport", main is trying to use the transports before they are loaded.

**Comment by abhidas17695** [comment]
@mitra42 please check out the latest commit. The fix you suggested worked. Thank you

**Comment by mitra42** [comment]
Will do

**Comment by mitra42** [comment]
I'm seeing it running twice on each load - Notice the line "resolving arc/archive.org" twice

**Comment by abhidas17695** [comment]
![screenshot 6](https://user-images.githubusercontent.com/21287808/43083789-eb4e016a-8eb4-11e8-9bb2-fce6375ca223.png)

That should not be happening. The flag `transportsLoaded` is used to load Dwebtransports just once. Looking into it.

**Comment by mitra42** [comment]
Sorry, I'm talking about a different problem, I wasn't clear. I think p_connect is running only once. Its loading a page twice - even when the URL dweb.archive.org is pasted in

**Comment by abhidas17695** [comment]
If you reload the extension and navigate to dweb.archive.org you will see that DwebTransports is loaded twice. And the URL is also captured twice. But if you then open a new tab and navigate to dweb.archive.org you will just see that the URL is captured twice. I think this has something to do with #28

**Comment by mitra42** [comment]
Agreed = if I turn off the preload the problem goes away - I'll mark this as closed.
