### ISSUE TITLE
Odd testing process

### ISSUE THREAD

**Issue by mitra42** [abhidas17695/dweb-ext#8]
Current process of  ... load extension; load page; reload extension; reload page 

Required because of bug @abhidas17695 saw with signatures.

**Comment by abhidas17695** [comment]
The current version 1.5 of the extension uses `require` to load the bundles into bootloader.js. After a new URL is intercepted the `require` caches are cleared and the bundles are loaded again. Lots of errors are logged to the console but the error `signature not verified` does not occur. What could be done to solve this issue without using this hacky solution ?

**Comment by mitra42** [comment]
See #14 regarding the signature.

**Comment by mitra42** [comment]
The odd test process no longer applies
