### ISSUE TITLE
Confirm p_boot works for bootloader.html and Firefox

### ISSUE THREAD

**Issue by mitra42** [abhidas17695/dweb-ext#9]
Code in Leaf.p_boot now has:
```
chrome.tabs.query({currentWindow:true,active:true},function(tabs){
     chrome.tabs.executeScript(tabs[0].id, { file:"scripts/redirect.js" }); 
     chrome.tabs.sendMessage(tabs[0].id, {url:url.href,target:opentarget});
});
```
Need to confirm this works in Firefox (do calls to "chrome" work there?), and also in bootloader.html.  If it doesnt then we need to parameterize p_resolveAndBoot e.g. with "bootFromExt=True" so that one piece of code works for both.

**Comment by abhidas17695** [comment]
Extension works with firefox.
